# Generated by Django 5.0.6 on 2024-06-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjajb', '0006_rename_date_meeting_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=16, unique=True)),
                ('callroom_time', models.TimeField()),
                ('gathering_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='cjajb.category')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='cjajb.competition')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='cjajb.meeting')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='cjajb.discipline')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='cjajb.scale')),
            ],
        ),
    ]
