name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      uses: abatilo/action-poetry@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install -r pyproject.toml
      working-directory: ./api/
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ./api/api/
